{{- if .Values.frontend.budget -}}
{{- if .Values.frontend.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gene-test.fullname" . }}-frontend
  labels:
    {{- include "gene-test.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.budget.minAvailable }}
  selector:
    matchLabels:
      {{- include "gene-test.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end -}}
{{- end -}}