apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "gene-test.fullname" . }}-frontend
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  podMetricsEndpoints:
  - port: "{{ .Values.frontend.service.port }}"
    targetPort: "{{ .Values.frontend.service.port }}"