apiVersion: v1
kind: Service
metadata:
  name: {{ include "gene-test.fullname" . }}-frontend
  labels:
    {{- include "gene-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    {{- include "gene-test.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
